name: Testing - main

on: [push, pull_request]


jobs:
  test:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [
          "ubuntu-latest",
          "macos-latest",
          # "windows-latest"
        ]
        python-version: ["3.7"]
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          echo "checking dirs"
          ls
          ls ..
          pwd
          conda install -c conda-forge rdkit openbabel
          python -m pip install --upgrade pip

          pip install -e .
      - name: pytest
        run: |
          pytest test --color=yes --cov=psp --cov-report html:coverage_reports
